name: Staging Deployment

on:
  push:
    branches:
      - staging
    paths-ignore:
      - .github/workflows/**

jobs:
  deploy_to_staging:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest

    environment:
      name: "staging"
      url: ${{ vars.URL }}

    steps:
      - name: Deploy to staging environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ./deploy_staging.sh next 
