name: Team Deployment

on:
  push:
    branches:
      - team-deploy

jobs:
  team_deployment:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [kimiko, cyborgs, starlight]

    environment:
      name: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Environment
        run: echo "Current environment is ${{ matrix.environment }}"
